# Generated by Django 4.2.3 on 2023-08-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matrimony", "0003_profile_sect"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hobby",
            options={"verbose_name_plural": "hobbies"},
        ),
    ]
